name: Pytest UV 并发示例

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  serial:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v6
      - name: 串行运行 pytest
        run: |
          seconds=$(uv run pytest | grep -oP '\d+\.\d+(?=s)' | tail -1)
          echo "串行执行耗时: $seconds 秒"
          if (( $(echo "$seconds <= 20" | bc -l) )); then
            echo "串行执行时间不满足要求（需大于20秒）"
            exit 1
          fi

  parallel_2:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v6
      - name: 2并发运行 pytest
        run: |
          seconds=$(uv run pytest -n 2 | grep -oP '\d+\.\d+(?=s)' | tail -1)
          echo "2并发执行耗时: $seconds 秒"
          if (( $(echo "$seconds <= 10" | bc -l) )) || (( $(echo "$seconds >= 20" | bc -l) )); then
            echo "2并发执行时间不满足要求（需大于10秒且小于20秒）"
            exit 1
          fi

  parallel_6:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v6
      - name: 6并发运行 pytest
        run: |
          seconds=$(uv run pytest -n 6 | grep -oP '\d+\.\d+(?=s)' | tail -1)
          echo "6并发执行耗时: $seconds 秒"
          if (( $(echo "$seconds <= 5" | bc -l) )) || (( $(echo "$seconds >= 10" | bc -l) )); then
            echo "6并发执行时间不满足要求（需大于5秒且小于10秒）"
            exit 1
          fi
